#!/bin/sh

PREREQ=""
prereqs()
{
	echo "$PREREQ"
}
case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac


echo 0 >/sys/class/android_usb/android0/enable || true
echo 18d1 >/sys/class/android_usb/android0/idVendor || true
echo D002 >/sys/class/android_usb/android0/idProduct || true
echo adb >/sys/class/android_usb/android0/functions || true
echo 1 >/sys/class/android_usb/android0/enable || true

echo 0 >/sys/module/kernel/parameters/panic || true

mkdir -p /system/bin
cp /bin/sh /system/bin/

echo "initrd: starting adbd for USB debugging" >/dev/kmsg || true

/sbin/adbd
wait $!
