#!/bin/sh -e

MINKVER="2.6.24"
PREREQ=""

# Output pre-requisites
prereqs() {
	echo "$PREREQ"
}

case "$1" in
prereqs)
	prereqs
	exit 0
	;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /sbin/swapon /sbin
copy_exec /usr/sbin/sgdisk /sbin
copy_exec /sbin/e2fsck /sbin
copy_exec /sbin/resize2fs /sbin
copy_exec /bin/chown /bin
copy_exec /bin/mount /bin
copy_exec /sbin/dumpe2fs /sbin

copy_exec /usr/share/initramfs-tools-ubuntu-touch/splash /
