#!/bin/sh -e

MINKVER="2.6.24"
PREREQ=""
DEB_HOST_MULTIARCH=$(dpkg-architecture -qDEB_HOST_MULTIARCH)

# Output pre-requisites
prereqs()
{
        echo "$PREREQ"
}

case "$1" in
    prereqs)
        prereqs
        exit 0
        ;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /sbin/swapon /sbin
copy_exec /sbin/e2fsck /sbin
copy_exec /bin/chown /bin
copy_exec /bin/mount /bin
copy_exec /sbin/dumpe2fs /sbin
copy_exec /lib/$DEB_HOST_MULTIARCH/libz.so.1
copy_exec /usr/lib/$DEB_HOST_MULTIARCH/libcrypto.so
copy_exec /usr/lib/$DEB_HOST_MULTIARCH/libdl.so
