#!/bin/sh

BOOT="LNX boot KERNEL"

for i in $BOOT; do
    path=$(find /dev -name "$i"|grep disk| head -1)
    [ -n "$path" ] && break
done

OLDCMDLINE="$(abootimg -i $path|grep cmdline|sed -e 's/^.*cmdline = //') "
echo $OLDCMDLINE| grep -q "empty cmdline" && OLDCMDLINE=""
for line in $OLDCMDLINE; do
	[ "$line" = "$1" ] || NEWCMDLINE="$NEWCMDLINE $line"
done

abootimg -u $path -c "cmdline=$NEWCMDLINE"
abootimg -i $path
